package rewire

// EXPERIMENTAL — design exploration for parallel-safe mocking.
//
// This file is a prototype only. It is not wired into the rewriter,
// so Mock_Foo wrappers generated by the current toolexec pipeline
// do NOT consult the goroutine-local table exposed here. To actually
// mock a function through this path, something has to call
// lookupParallelMock ahead of the normal Mock_Foo nil check.
//
// Goroutine identification uses the pprof profile labels pointer as
// a goroutine-unique key:
//
//   - Tests that install a FuncParallel mock push a unique pprof
//     label onto the current goroutine. pprof labels are stored on
//     the g struct, which gives us per-goroutine isolation.
//   - Child goroutines inherit their parent's labels automatically
//     (Go runtime behavior), so a child goroutine reads the same
//     pointer as its parent test — it sees the parent's mocks
//     "for free," no rewire.Go helper needed.
//   - Reading the pointer without a context requires one linkname
//     (runtime/pprof.runtime_getProfLabel). Go 1.23+ restricted
//     direct pull from runtime.* symbols, but pprof's re-exported
//     stub is reachable because runtime pushes the symbol out via
//     its own go:linkname. Not a guaranteed-stable API — could be
//     closed in a future Go release; fallback would be stack-walk
//     (~1 μs per call, pure public API).
//
// See plans/parallel_test_safety_design.md for the full option
// space and pprof_label_probe_test.go for the gating tests that
// proved the mechanism works on Go 1.26.2.

import (
	"context"
	"fmt"
	"reflect"
	"runtime"
	"runtime/pprof"
	"sync"
	"sync/atomic"
	"testing"
	"unsafe"
	_ "unsafe" // for go:linkname
)

// runtimeGetProfLabel returns the raw labels pointer stored on the
// current goroutine's g struct. Nil if the goroutine has no labels
// and is not a child of a goroutine that does.
//
// Linkname target is runtime/pprof.runtime_getProfLabel rather than
// runtime.getProfLabel: the former is reachable from third-party
// code under Go 1.23+ rules (runtime pushes the symbol out, pprof's
// stub becomes linker-visible), the latter is blocked by the
// restriction on pulling runtime-internal symbols.
//
//go:linkname runtimeGetProfLabel runtime/pprof.runtime_getProfLabel
func runtimeGetProfLabel() unsafe.Pointer

// goroutineMocks maps goroutine-labels-pointer → *sync.Map (funcName
// → replacement fn). The outer key is the pprof labels pointer,
// which is stable for the life of a labeled goroutine and inherited
// by child goroutines.
//
// Using uintptr for the key lets us compare pointers without the GC
// needing to track them — pprof holds the labels alive via the g
// struct, so we don't risk dangling references.
var goroutineMocks sync.Map

// nextParallelScopeID supplies unique IDs for the rewire.scope pprof
// label so each test's goroutine gets distinct labels (and therefore
// a distinct pointer to key on).
var nextParallelScopeID atomic.Uint64

// ensureGoroutineLabeled guarantees the current goroutine has a
// pprof labels pointer set. If none is present (nil), it installs a
// labels set with a unique rewire.scope value. Idempotent: if
// labels are already present (installed by an earlier FuncParallel
// call, by pprof.Do in user code, or inherited from a parent), this
// is a no-op beyond the probe.
//
// Returns the current labels pointer as uintptr for use as a map
// key.
func ensureGoroutineLabeled() uintptr {
	if ptr := runtimeGetProfLabel(); ptr != nil {
		return uintptr(ptr)
	}
	id := nextParallelScopeID.Add(1)
	ctx := pprof.WithLabels(
		context.Background(),
		pprof.Labels("rewire.scope", fmt.Sprintf("%d", id)),
	)
	pprof.SetGoroutineLabels(ctx)
	return uintptr(runtimeGetProfLabel())
}

// FuncParallel installs a goroutine-local mock for target, scoped to
// t's lifetime via t.Cleanup. The mock is visible to calls
// originating from t's goroutine AND to calls made from goroutines
// spawned by t (directly or transitively, via raw `go`) — child
// inheritance comes from pprof labels propagation in the Go
// runtime.
//
// Use this inside t.Parallel() tests where two tests in the same
// package want to mock the same target with different replacements
// without racing on a shared Mock_Foo variable.
//
// EXPERIMENTAL: not yet wired into the rewriter. See the package
// comment above.
func FuncParallel[F any](t *testing.T, target F, replacement F) {
	t.Helper()
	name := runtime.FuncForPC(reflect.ValueOf(target).Pointer()).Name()
	key := ensureGoroutineLabeled()

	rawTable, _ := goroutineMocks.LoadOrStore(key, &sync.Map{})
	table := rawTable.(*sync.Map)
	table.Store(name, replacement)

	t.Cleanup(func() {
		table.Delete(name)
		// Don't delete the goroutine's entire table entry — the
		// test's goroutine may be reused for cleanup tasks and
		// concurrent FuncParallel calls on other targets share the
		// same key. The inner table's entries are cleared as their
		// individual Cleanups fire; the outer map entry ends up
		// pointing at an empty *sync.Map, which is cheap and
		// reclaimed when the goroutine ends and a later run in the
		// same g slot overwrites the key with a fresh table.
	})
}

// lookupParallelMock returns the replacement function installed via
// FuncParallel that's visible to the current goroutine, or
// (nil, false) if none. This is the hook a rewriter-generated
// wrapper would call ahead of the existing Mock_Foo nil check on
// parallel-enabled targets.
//
// EXPERIMENTAL.
func lookupParallelMock(name string) (any, bool) {
	ptr := runtimeGetProfLabel()
	if ptr == nil {
		return nil, false
	}
	rawTable, ok := goroutineMocks.Load(uintptr(ptr))
	if !ok {
		return nil, false
	}
	return rawTable.(*sync.Map).Load(name)
}
