package rewire

// EXPERIMENTAL — design exploration for parallel-safe mocking.
//
// This file is a prototype only. It is not wired into the rewriter,
// so Mock_Foo wrappers generated by the current toolexec pipeline
// do NOT consult the goroutine-local table exposed here. To actually
// mock a function through this path, something has to call
// lookupParallelMock ahead of the normal Mock_Foo nil check.
//
// The tests in parallel_experimental_test.go exercise the runtime
// via a stand-in wrapper, which is enough to demonstrate that
// goroutine-local dispatch works, goroutines with different mocks
// don't interfere, and the Go child-handoff carries mocks correctly.
//
// See plans/parallel_test_safety_design.md for the full option
// space, cost analysis, and explanation of why this API shape was
// chosen over the alternatives considered.

import (
	"bytes"
	"reflect"
	"runtime"
	"strconv"
	"sync"
	"testing"
)

// currentGoid returns the current goroutine's runtime-internal ID
// by parsing the first line of runtime.Stack output (format:
// "goroutine NNN [status]:\n..."). The ID is unique within a
// process's lifetime and stable for the life of a goroutine, which
// is all we need as a map key for per-goroutine state.
//
// Stack parsing is ~1000× slower than a linkname lookup of
// runtime.goid (microseconds vs nanoseconds), but Go 1.23+
// restricted pull-side linkname access to private runtime symbols
// including runtime.goid, so Stack parsing is the portable option.
// A production-quality version of parallel mocking would want the
// linkname speed; for a prototype the cost is well below the noise
// floor of per-test overhead.
func currentGoid() int64 {
	var buf [64]byte
	n := runtime.Stack(buf[:], false)
	text := bytes.TrimPrefix(buf[:n], []byte("goroutine "))
	if before, _, ok := bytes.Cut(text, []byte(" ")); ok {
		id, _ := strconv.ParseInt(string(before), 10, 64)
		return id
	}
	return 0
}

// goroutineMocks is the prototype's central store: goid → *sync.Map
// where each inner map is funcName → replacement-fn-as-any. Keyed
// on goid because that's the finest-grained "current execution
// context" Go exposes.
//
// Uses sync.Map for two reasons: (a) entries are rarely deleted
// compared to reads, which matches sync.Map's intended workload,
// and (b) the prototype avoids a package-level mutex on the hot
// path.
var goroutineMocks sync.Map

// FuncParallel installs a goroutine-local mock for target, scoped to
// t's lifetime via t.Cleanup. The mock is visible only to calls
// originating from t's goroutine (or goroutines spawned from it via
// rewire.Go); goroutines spawned with the raw `go` keyword do NOT
// see it.
//
// Use this inside t.Parallel() tests where two tests in the same
// package want to mock the same target with different replacements
// without racing on a shared Mock_Foo variable.
//
// EXPERIMENTAL: not yet wired into the rewriter. See the package
// comment above.
func FuncParallel[F any](t *testing.T, target F, replacement F) {
	t.Helper()
	name := runtime.FuncForPC(reflect.ValueOf(target).Pointer()).Name()
	gid := currentGoid()

	rawTable, _ := goroutineMocks.LoadOrStore(gid, &sync.Map{})
	table := rawTable.(*sync.Map)
	table.Store(name, replacement)

	t.Cleanup(func() {
		table.Delete(name)
		// Intentionally do not delete the goid entry itself: the
		// map may still carry other targets installed by the same
		// test, and empty inner maps are cheap. They'll be
		// reclaimed naturally when the goroutine terminates (via
		// runtime GC pressure) or when a later test reuses the
		// goid and overwrites the entry.
	})
}

// Go spawns fn in a goroutine that inherits a snapshot of the
// calling goroutine's FuncParallel mock table. Use instead of
// `go fn()` inside a parallel test when the child goroutine needs
// to see the parent's mocks.
//
// The child's mocks are cleared when fn returns. The parent's
// table is unaffected — child edits don't propagate back.
//
// EXPERIMENTAL.
func Go(t *testing.T, fn func()) {
	t.Helper()
	parentGid := currentGoid()
	rawParent, hasParent := goroutineMocks.Load(parentGid)

	go func() {
		childGid := currentGoid()
		if hasParent {
			// Copy parent entries into a fresh child map. A shared
			// reference would tangle the parent's Cleanup with the
			// child's lifetime and make concurrent edits between
			// parent and child visible to each other — not what
			// per-goroutine isolation means.
			child := &sync.Map{}
			rawParent.(*sync.Map).Range(func(k, v any) bool {
				child.Store(k, v)
				return true
			})
			goroutineMocks.Store(childGid, child)
			defer goroutineMocks.Delete(childGid)
		}
		fn()
	}()
}

// lookupParallelMock returns the replacement function installed via
// FuncParallel for the current goroutine's target, or (nil, false)
// if none. This is the hook a rewriter-generated wrapper would call
// ahead of the existing Mock_Foo nil check on parallel-enabled
// targets.
//
// Exported from the package so the prototype's stand-in wrapper can
// exercise it; in a wired implementation the rewriter would emit
// the same call site.
//
// EXPERIMENTAL.
func lookupParallelMock(name string) (any, bool) {
	rawTable, ok := goroutineMocks.Load(currentGoid())
	if !ok {
		return nil, false
	}
	return rawTable.(*sync.Map).Load(name)
}
