package rewire

import "testing"

// Replace swaps the value at target with replacement for the duration of the test.
// Use it to activate a mock that was generated by the rewire rewrite command.
//
// Usage:
//
//	rewire.Replace(t, &bar.Mock_Hello, func(name string) string {
//	    return "mocked"
//	})
func Replace[F any](t *testing.T, target *F, replacement F) {
	t.Helper()
	old := *target
	*target = replacement
	t.Cleanup(func() { *target = old })
}
